services:
  node-arkeo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arkeo-node
    ports:
      - "26656:26656"
      - "26660:26660"
    restart: unless-stopped
    volumes:
      - arkeo_volume:/app/.arkeo
      - ./entrypoint.sh:/app/entrypoint.sh
      - arkeo_bin:/app/go

volumes:
  arkeo_volume:
  arkeo_bin:
